// Copyright 2023 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DEFAULT_MMIO_TEST_DTS_REG_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DEFAULT_MMIO_TEST_DTS_REG_H_

#define REG_UNIT_NAME AAAAAAAAA
#define REG_A_BASE 0xAAAAAAAA
#define REG_A_LENGTH 0x2000
#define REG_B_BASE_WORD0 0xFAFAFAFA
#define REG_B_BASE_WORD1 0xBBBBBBBB
#define REG_B_LENGTH_WORD0 0x0
#define REG_B_LENGTH_WORD1 0x3000
#define REG_C_BASE_WORD0 0x0
#define REG_C_BASE_WORD1 0xCCCCCCCC
#define REG_C_LENGTH_WORD0 0x10000010
#define REG_C_LENGTH_WORD1 0x4000

#define RANGE_UNIT_NAME FFFF0000
#define RANGE_BASE 0xFFFF0000
#define RANGE_SIZE 0x1000

#define I2C_CHILD_UNIT 23
#define I2C_CHILD_ADDRESS 0x23

#define RANGE_OFFSET_UNIT ABC
#define RANGE_OFFSET 0x0ABC
#define RANGE_OFFSET_SIZE 0x0100

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DEFAULT_MMIO_TEST_DTS_REG_H_
