#!/bin/bash
# Copyright 2022 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### print the Bazel workspace directory

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
fx-config-read

# LINT.IfChange
echo "${FUCHSIA_BUILD_DIR}/gen/build/bazel/workspace"
# LINT.ThenChange(/build/bazel/bazel_workspace.gni)
