#!/bin/bash
# Copyright 2021 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Software delivery
set -e

# TODO(b/278592638): Remove this entirely.
printf "report-bug has been removed as it was incompatible with Metadata files.\n"
printf "Please file bugs against the component listed in the nearest METADATA.textproto file.\n"
printf "Questions? Email cflewis@google.com\n"
exit 0
