// Copyright 2023 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_REGISTERS_TEST_DTS_REGISTERS_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_REGISTERS_TEST_DTS_REGISTERS_H_

#define REGISTER_OFFSET1 0x8
#define REGISTER_LENGTH1 0x1
#define REGISTER_MASK1 0x04

#define REGISTER_OFFSET2 0x84
#define REGISTER_LENGTH2 0x8
#define REGISTER_MASK2_0 0x00003000
#define REGISTER_MASK2_1 0x10000000

#define REGISTER_OFFSET3 0x100
#define REGISTER_LENGTH3 0x4
#define REGISTER_MASK3 0xFF000000
#define REGISTER_NAME3 "reset"

#define REGISTER_OFFSET4 0x10
#define REGISTER_LENGTH4 0x2
#define REGISTER_MASK4 0x0FF0
#define REGISTER_NAME4 "reset2"

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_REGISTERS_TEST_DTS_REGISTERS_H_
