#!/bin/bash
# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### query the GN build graph

## usage: fx gn-desc ...

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read

DESC_TARGET="host-tools/gn_desc"
DESC_BIN="${FUCHSIA_BUILD_DIR}/${DESC_TARGET}"

if [[ "$1" == "--no-build" ]]; then
  shift # remove this arg so the rest can be passed to the binary
  if [ ! -f "$DESC_BIN" ]; then
    fx-error "--no-build was specified, but $DESC_BIN does not exist."
    fx-error "Rerun without --no-build to build gn_desc."
    exit 1
  fi
else
  fx-command-run build ${DESC_TARGET} || ( \
    fx-error "Failed to build gn_desc."; \
    exit 1
  )
fi

(cd $FUCHSIA_DIR; $DESC_BIN \
    --file "${FUCHSIA_BUILD_DIR}/gn_desc.json" \
    "$@")
