#!/bin/bash
# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Software delivery
### check if the incremental publisher is running
##
## This command is to be used primarily by other commands, such as `fx test`.
##

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"/lib/updates.sh || exit $?
fx-config-read

if [[ $# -ne 0 ]]; then
  fx-command-help
  exit 1
fi

check-for-incremental-publisher || exit 1
