#!/bin/bash
# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Software delivery
### publish a set of packages

## usage: fx publish cache
##
## Publishes a given set of packages.
## Currently only cache packages can be published.

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source "$SCRIPT_DIR/../lib/vars.sh" || exit $?

fx-config-read
cd $FUCHSIA_BUILD_DIR && "${PREBUILT_PYTHON3_DIR}/bin/python3.8" "$SCRIPT_DIR"/publish.py "$@"
