#!/bin/bash
# Copyright 2021 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Source tree
### updates OWNERS files for third_party dependencies

## usage: fx update-3p-owners  [--num-threads N]
##                             [--rust-metadata FILE]
##                             [--integration-manifest FILE]
##                             [--skip-rustc-3p-update]
##                             [--skip-existing]
##
## Updates OWNERS files for projects, based on gn target references. For any
## given project, the tool adds as owners the owners of the projects that depend
## on that project.
##
##
## Arguments:
## --num-threads N:               run on N threads.
##
## --rust-metadata FILE:          update OWNERS for the projects specified in
##                                the rust metadata JSON FILE.
##
## --integration-manifest FILE:   update OWNERS for the projects specified in
##                                the integration manifest XML FILE.
##
## --skip-existing:               only generate OWNERS files for projects
##                                missing owners; does not update existing
##                                OWNERS files.
##
## --skip-rustc-3p-update:        skip updating rustc_library and rustc_binary
##                                third_party dependencies.
##
##
## See https://fuchsia.dev/fuchsia-src/development/languages/rust/third_party.md
## for more details.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read

OWNERS_TOOL_TARGET="host-tools/auto_owners"
OWNERS_TOOL_BIN="${FUCHSIA_BUILD_DIR}/${OWNERS_TOOL_TARGET}"

# Parse arguments
while [[ $# -ge 1 ]]; do
  case "$1" in
    -h|--help)
      fx-command-help
      exit 0
      ;;
    --num-threads)
      shift
      [[ ! $1 ]] && die "--num-threads requires an argument after it"
      NUM_THREADS="--num-threads $1"
      ;;
    --rust-metadata)
      shift
      [[ ! $1 ]] && die "--rust-metadata requires an argument after it"
      RUST_METADATA="--rust-metadata $1"
      ;;
    --integration-manifest)
      shift
      [[ ! $1 ]] && die "--integration-manifest requires an argument after it"
      INTEGRATION_MANIFEST="--integration-manifest $1"
      ;;
    --skip-rustc-3p-update)
      SKIP_RUSTC_3P_UPDATE="true"
      ;;
    --skip-existing)
      SKIP_EXISTING="--skip-existing"
      ;;
    -*)
      echo "Cannot understand option $1"
      exit 1
      ;;
  esac
  shift
done

if [[ ! -n "$NUM_THREADS" ]]; then
  fx-error "Must specify --num-threads. Recommended value is NCPUS / 2 or less."
  fx-error "NOTE: using all cores can deadlock your kernel. See https://fxbug.dev/75382."
  exit 1
fi

if [[ -z "$RUST_METADATA" ]] && [[ -z "$INTEGRATION_MANIFEST" ]]; then
  fx-warn "No project OWNERS will be updated."
  fx-warn "Use [ --rust-metadata | --integration-manifest ] to specify projects."
fi

fx-command-run build ${OWNERS_TOOL_TARGET} || ( \
  fx-error "Failed to build owners tool."; \
  exit 1
)

if [[ ! -n "$SKIP_RUSTC_3P_UPDATE" ]]; then
  fx-command-run update-rustc-third-party || ( \
    fx-error "Failed to run rustc 3p update script."; \
    exit 1
  )
fi

(cd $FUCHSIA_DIR; $OWNERS_TOOL_BIN \
  $NUM_THREADS \
  $RUST_METADATA \
  $INTEGRATION_MANIFEST \
  --overrides $FUCHSIA_DIR/third_party/rust_crates/owners.toml \
  --out-dir $FUCHSIA_BUILD_DIR \
  --gn-bin $PREBUILT_GN \
  $SKIP_EXISTING)
