# proto-file: tools/metadata/proto/metadata.proto
# proto-message: Metadata
# https://fuchsia.dev/fuchsia-src/development/source_code/metadata

last_reviewed_date: {
  year: 2023
  month: 4
  day: 17
}

trackers: {
  issue_tracker: {
    component_id: 1478377
  }
}
