[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../third_party/rust_crates/vendor"

[build]
target-dir = "../out/cargo_target"
rustflags = ["-Wrust-2018-idioms"]

# Override the harfbuzz and freetype crates' build scripts, and instead link to our existing
# versions of the native libraries.
# See https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts.
# Keep in sync with //third_party/rust_crates/.cargo/config.

[target.x86_64-fuchsia.harfbuzz]
rustc-link-lib = ["harfbuzz"]

[target.x86_64-unknown-linux-gnu.harfbuzz]
rustc-link-lib = ["harfbuzz"]

[target.x86_64-apple-darwin.harfbuzz]
rustc-link-lib = ["harfbuzz"]

[target.x86_64-fuchsia.freetype]
rustc-link-lib = ["freetype2"]

[target.x86_64-unknown-linux-gnu.freetype]
rustc-link-lib = ["freetype2"]

[target.x86_64-apple-darwin.freetype]
rustc-link-lib = ["freetype2"]
