[zxdb] b main
Created Breakpoint 1 @ main

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/bitfield.cm
🛑 on bp 1 main() • bitfield.cc:??

[zxdb] p -d p
(*)0x?? ➔ {
  Parent1 = {field0 = 2}
  Parent2 = {field1 = 0, field2 = -43}
  field3 = 8
  field4 = 3
  field5 = 482
  field6 = 7
}

[zxdb] p p->field5 = 0
0

[zxdb] p -d p
(*)0x?? ➔ {
  Parent1 = {field0 = 2}
  Parent2 = {field1 = 0, field2 = -43}
  field3 = 8
  field4 = 3
  field5 = 0
  field6 = 7
}

[zxdb] p p->field1 = -1
'\xff'

[zxdb] p -d p
(*)0x?? ➔ {
  Parent1 = {field0 = 2}
  Parent2 = {field1 = -1, field2 = -43}
  field3 = 8
  field4 = 3
  field5 = 0
  field6 = 7
}
