# TODO(fxbug.dev/117067): fix the flake and reenable the test on arm64 targets.
## require target_cpu=x64

[zxdb] break loop.cc:9 if i > 2
Created Breakpoint 1 condition="i > 2" @ loop.cc:9

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/loop.cm
Launched Process 1 state=Running koid=?? name=loop.cm component=loop.cm
Breakpoint 1 now matching 1 addrs for loop.cc:9
🛑 on bp 1 do_loop(int) • loop.cc:9

[zxdb] p i
3

[zxdb] c
🛑 on bp 1 do_loop(int) • loop.cc:9

[zxdb] p i
4

[zxdb] c
Process 1 exited with code 0.
