## require optimize=none
[zxdb] b $main
Created Breakpoint 1 @ $main
Pending: No current matches for location. It will be matched against new
         processes and shared libraries.

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/cpp_functions.cm
run-component won't work for many v2 components. See "help run-component".
Launched Process 1 state=Running koid=?? name=cpp_functions.cm component=cpp_functions.cm
Breakpoint 1 now matching 1 addrs for $main
🛑 on bp 1 main() • cpp_functions.cc:??

# Make sure the return value is captured.
[zxdb] p ReturnGlobalPlusOne()
🛑 on bp 1 main() • cpp_functions.cc:??
1

# Should be able to chain return values with more expressions.
[zxdb] p ReturnGlobalPlusOne() - 1
🛑 on bp 1 main() • cpp_functions.cc:??
0

# TODO(https://fxbug.dev/129958): this should also work as
#        ReturnGlobalPlusOne() - 1 == SomeGlobal
[zxdb] p SomeGlobal == ReturnGlobalPlusOne() - 1
🛑 on bp 1 main() • cpp_functions.cc:??
true

# Pointers should also work.
[zxdb] p GetIntPointer()
🛑 on bp 1 main() • cpp_functions.cc:??
(*)0x?? ➔ 0

# Expressions should be able to dereference pointer return types.
[zxdb] p *GetIntPointer() * 2
🛑 on bp 1 main() • cpp_functions.cc:??
0

# Other built in types should work.
[zxdb] p GetFloat()
🛑 on bp 1 main() • cpp_functions.cc:??
3.14159

[zxdb] p GetCharPtr()
🛑 on bp 1 main() • cpp_functions.cc:??
Hello!

[zxdb] c
Process 1 exited with code 0.
