# Starnix doesn't work with asan right now.
## require is_asan=false
## set timeout 10

# TODO(fxbug.dev/127384): attach shouldn't be necessary.
[zxdb] attach hello_starnix
Waiting for process matching "hello_starnix".

[zxdb] b hello_starnix.cc:9
Created Breakpoint 1 @ hello_starnix.cc:9

[zxdb] run-test fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/hello_starnix.cm
Attached Process 1 state=Running koid=?? name=hello_starnix component=starnix_kernel.cm
🛑 on bp 1 main() • hello_starnix.cc:9

[zxdb] next
🛑 main() • hello_starnix.cc:10

[zxdb] b execute_syscall
Created Breakpoint 2 @ execute_syscall

[zxdb] c
🛑 on bp 2

# Zxdb can unwind into restricted stack.
[zxdb] f
# When optimization is on, there might be other inlined frame so we only check
# the existence of execute_syscall and main function in the backtrace.
execute_syscall
main() • hello_starnix.cc

[zxdb] bp rm
Removed Breakpoint 2 @ execute_syscall

[zxdb] c
Process 1 exited with code 0.
