# Starnix doesn't work with asan right now. LTO can cause execute_syscall to be inlined
# which breaks unwinding into user code.
## require is_asan=false
## require is_lto=false
## require is_thinlto=false
## require optimize=none
## set timeout 10

# TODO(fxbug.dev/127384): attach shouldn't be necessary.
[zxdb] attach hello_starnix
Waiting for process matching "hello_starnix".

[zxdb] b hello_starnix.cc:9
Created Breakpoint 1 @ hello_starnix.cc:9

[zxdb] run-test --realm /core/testing:system-tests fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/hello_starnix.cm
Attached Process 1 state=Running koid=?? name=hello_starnix component=starnix_kernel.cm
🛑 on bp 1 main() • hello_starnix.cc:9

[zxdb] next
🛑 main() • hello_starnix.cc:10

# TODO(fxbug.dev/131121): We should use hardware breakpoints here but they don't work on arm64.
[zxdb] b sys_exit_group
Created Breakpoint 2 @ sys_exit_group

[zxdb] c
🛑 on bp 2

# Zxdb can unwind into restricted stack.
[zxdb] f
# When optimization is on, there might be other inlined frame so we only check
# the existence of sys_exit_group and main function in the backtrace.
sys_exit_group
main() • hello_starnix.cc

[zxdb] bp rm
Removed Breakpoint 2 @ sys_exit_group

[zxdb] c
Process 1 exited with code 0.
