# TODO: the line number for the topmost frame should be 5 but is 7 when optimization is on.

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/inlined_crasher.cm
Launched Process 1 state=Running koid=?? name=inlined_crasher.cm component=inlined_crasher.cm
🛑 f0() • inlined_crasher.cc:??

[zxdb] f -r
▶ 0 f0() • inlined_crasher.cc:?? (inline)
  1 f1() • inlined_crasher.cc:7
  2 f2() • inlined_crasher.cc:9 (inline)
  3 f3() • inlined_crasher.cc:11
  4 main() • inlined_crasher.cc:13
  5 call_main(…) • __libc_start_main.c:64 (inline)
  6 start_main(…)
  7 __libc_start_main(…)
  8 _start(…)

[zxdb] kill
Process 1 killed.
