## require optimize=none
[zxdb] b $main
Created Breakpoint 1 @ $main
Pending: No current matches for location. It will be matched against new
         processes and shared libraries.

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/rust_functions.cm
run-component won't work for many v2 components. See "help run-component".
Launched Process 1 state=Running koid=?? name=rust_functions.cm component=rust_functions.cm
Breakpoint 1 now matching 1 addrs for $main
🛑 on bp 1 rust_functions::main() • rust_functions.rs:??

# Make sure the return value is captured.
[zxdb] p rust_functions::return_global_plus_one()
🛑 on bp 1 rust_functions::main() • rust_functions.rs:??
1

# Return values can be used in expressions.
[zxdb] p rust_functions::return_global_plus_one() - 1
🛑 on bp 1 rust_functions::main() • rust_functions.rs:??
0

# TODO(https://fxbug.dev/129958): this should also work as
#        rust_functions::return_global_plus_one() - 1 == SOME_GLOBAL
[zxdb] p SOME_GLOBAL == rust_functions::return_global_plus_one() - 1
🛑 on bp 1 rust_functions::main() • rust_functions.rs:??
true

# Other built-in types should also work
[zxdb] p rust_functions::return_i32_box()
🛑 on bp 1 rust_functions::main() • rust_functions.rs:??
(*)0x?? ➔ 0

# Expressions should be able to dereference pointer return types.
[zxdb] p *rust_functions::return_i32_box() + 1
🛑 on bp 1 rust_functions::main() • rust_functions.rs:??
1

[zxdb] p rust_functions::return_float()
🛑 on bp 1 rust_functions::main() • rust_functions.rs:??
3.14159

## Rust strings are more complicated than C++ char* and will require more robust type support.

[zxdb] c
Process 1 exited with code 0.
