[zxdb] break blind_write
Created Breakpoint 1 @ blind_write
Pending: No current matches for location. It will be matched against new
         processes and shared libraries.

[zxdb] run-component fuchsia-pkg://fuchsia.com/crasher#meta/cpp_crasher.cm
Launched Process 1 state=Running koid=?? name=cpp_crasher.cm component=cpp_crasher.cm
Breakpoint 1 now matching ?? addrs for blind_write
🛑 on bp 1 blind_write(volatile unsigned int*) • crasher.c:??

[zxdb] c
 Process 1 (koid=??) thread 1 (koid=??)
 Faulting instruction: ??

[zxdb] b
Created Breakpoint 2??@ ../../src/developer/forensics/crasher/cpp/crasher.c:??

[zxdb] k
Process 1 killed.
