# TODO: find out if rust code will also have the simple-template-names flag

[zxdb] b template_types.cc:110
Created Breakpoint 1 @ template_types.cc:110
Pending: No current matches for location. It will be matched against new
         processes and shared libraries.

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/simplified_templates.cm
⚠️  run-component won't work for many v2 components. See "help run-component".
Launched Process 1 state=Running koid=?? name=simplified_templates.cm component=simplified_templates.cm

🛑 on bp 1 main() • template_types.cc:110
[zxdb] locals -t
(MyStruct<false>) bar = {}
(MyStruct<true>) foo = {}
(MyClass<double>) mcd = {(double) my_t_ = 48.3}
(MyDoubleTemplate<double, unsigned long>) mdtd64 = {
  (double) my_t_ = 12.4
  (unsigned long) my_u_ = 274704
}
(MyTemplateValueClass<5>) mtvc = {(const int) my_k_ = 5}
(MyTemplateValueClassChar<'f'>) mtvcc = {(const char) my_c_ = 'f'}
(MyDoubleTemplate<int, char>) my_double_template = {
  (int) my_t_ = 5
  (char) my_u_ = 'c'
}
(MyClass<char>) myclass = {(char) my_t_ = 'c'}
(MyClass<int>) myi = {(int) my_num_ = 12}

[zxdb] continue
Process 1 exited with code 0.
