# TODO(jruthe): find out if rust code will also have the simple-template-names flag
## require optimize=none

[zxdb] b template_types.cc:110
Created Breakpoint 1 @ template_types.cc:??
Pending: No current matches for location. It will be matched against new
         processes and shared libraries.

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/simplified_templates.cm
⚠️  run-component won't work for many v2 components. See "help run-component".
Launched Process 1 state=Running koid=?? name=simplified_templates.cm component=simplified_templates.cm

🛑 on bp 1 main() • template_types.cc:??
[zxdb] locals -t
(MyStruct<false>) bar = {}
(MyStruct<true>) foo = {}
(MyClass<double>) mcd = {(double) my_t_ = 48.3}
(MyDoubleTemplate<double, unsigned long>) mdtd64 = {
  (double) my_t_ = 12.4
  (unsigned long) my_u_ = 274704
}
(MyTemplateValueClass<5>) mtvc = {(const int) my_k_ = 5}
(MyTemplateValueClassChar<'f'>) mtvcc = {(const char) my_c_ = 'f'}
(MyDoubleTemplate<int, char>) my_double_template = {
  (int) my_t_ = 5
  (char) my_u_ = 'c'
}
(MyClass<char>) myclass = {(char) my_t_ = 'c'}
(MyClass<int>) myi = {(int) my_num_ = 12}

[zxdb] sym-info ToString<double>
Function: ToString(double)
  DWARF tag: DW_TAG_subprogram (0x2e) @ offset ??
  Linkage name: _Z8ToStringIdENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEET_
  Declaration: ../../src/developer/debug/e2e_tests/inferiors/template_types.cc:??
  Code ranges [begin, end-non-inclusive):
    [??, ??)
  Frame base (address range + DWARF expression):
    <default>: register(??)
  Return type: std::__2::string

[zxdb] sym-info ToString<int>
Function: ToString(int)
  DWARF tag: DW_TAG_subprogram (0x2e) @ offset ??
  Linkage name: _Z8ToStringIiENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEET_
  Declaration: ../../src/developer/debug/e2e_tests/inferiors/template_types.cc:??
  Code ranges [begin, end-non-inclusive):
    [??, ??)
  Frame base (address range + DWARF expression):
    <default>: register(??)
  Return type: std::__2::string


[zxdb] continue
Process 1 exited with code 0.
