# On x64-release, all doubles become nan.
## require optimize=none

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/simplified_templates.cm
Launched Process 1 state=Running koid=?? name=simplified_templates.cm component=simplified_templates.cm
🛑 debug::BreakIntoDebuggerIfAttached()

[zxdb] up
Frame 1 main() • simplified_templates.cc

[zxdb] locals -t
(MyStruct<false>) bar = {}
(MyStruct<true>) foo = {}
(MyClass<double>) mcd = {(double) my_t_ = 48.3}
(MyDoubleTemplate<double, unsigned long>) mdtd64 = {
  (double) my_t_ = 12.4
  (unsigned long) my_u_ = 274704
}
(MyTemplateValueClass<5>) mtvc = {(const int) my_k_ = 5}
(MyTemplateValueClassChar<'f'>) mtvcc = {(const char) my_c_ = 'f'}
(MyDoubleTemplate<int, char>) my_double_template = {
  (int) my_t_ = 5
  (char) my_u_ = 'c'
}
(MyClass<char>) myclass = {(char) my_t_ = 'c'}
(MyClass<int>) myi = {(int) my_num_ = 12}

[zxdb] sym-info ToString<double>
Function: ToString<double>(double)
  DWARF tag: DW_TAG_subprogram (0x2e) @ offset ??
  Linkage name: _Z8ToStringIdENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEET_
  Declaration: ../../src/developer/debug/e2e_tests/inferiors/simplified_templates.cc:??
  Code ranges [begin, end-non-inclusive):
    [??, ??)
  Frame base (address range + DWARF expression):
    <default>: register(??)
  Return type: std::__2::string

[zxdb] sym-info ToString<int>
Function: ToString<int>(int)
  DWARF tag: DW_TAG_subprogram (0x2e) @ offset ??
  Linkage name: _Z8ToStringIiENSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEET_
  Declaration: ../../src/developer/debug/e2e_tests/inferiors/simplified_templates.cc:??
  Code ranges [begin, end-non-inclusive):
    [??, ??)
  Frame base (address range + DWARF expression):
    <default>: register(??)
  Return type: std::__2::string


[zxdb] continue
Process 1 exited with code 0.
