[zxdb] break step_plt.cc:12
Created Breakpoint 1 @ step_plt.cc:12

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/step_plt.cm
Launched Process 1 state=Running koid=?? name=step_plt.cm component=step_plt.cm
Breakpoint 1 now matching 1 addrs for step_plt.cc:12
🛑 on bp 1 main() • step_plt.cc:12

[zxdb] next
🛑 main() • step_plt.cc:13

[zxdb] f
▶ 0 main() • step_plt.cc:13
  1…4 «libc startup» (-r expands)

[zxdb] next
🛑 main() • step_plt.cc:14

[zxdb] c
Process 1 exited with code 0.
