# proto-file: tools/metadata/proto/metadata.proto
# proto-message: Metadata
# https://fuchsia.dev/fuchsia-src/development/source_code/metadata

last_reviewed_date: {
  year: 2023
  month: 8
  day: 28
}

trackers: {
  # TODO(fxbug.dev/132769): Migrate Flake fetcher to Buganizer. This component
  # is for Flake fetcher use only. Use `Starnix` component for all other issues.
  monorail: {
    project: "fuchsia"
    component: "StarnixFlakes"
  }
  # Buganizer component id for `starnix` public component.
  issue_tracker: {
    component_id: 1396624
  }
}

presubmits: {
  review_notify: "fuchsia-starnix-firehose+reviews@google.com"
}
