# proto-file: tools/metadata/proto/metadata.proto
# proto-message: Metadata
# https://fuchsia.dev/fuchsia-src/development/source_code/metadata

last_reviewed_date: {
  year: 2023
  month: 4
  day: 17
}

trackers: {
  monorail: {
    project: "fuchsia"
    component: "Diagnostics>Logs"
  }
}
